### ISSUE TITLE
IDEA: Transfer to new map every ~10 waves?

### ISSUE THREAD

**Issue by bountygiver** [GuerrillaWar/WaveCOM#4]
There's a X2Action_TransferToNewMission that allows you to copy all units you control and move them to another mission, since the HQ state is also copied, progression will not be lost, but it can potentially solve performance issues as the game state history is probably cleaned after a transfer (and a flat map after many waves)

**Comment by MalucoMarinero** [comment]
interesting, worth investigating because we can't flush rubble as yet. If it can be done cleanly, it'd make a huge difference to the long game.

**Comment by bountygiver** [comment]
Newest update had the map transfer working, now we just need a UI and trigger condition for it.

**Comment by bountygiver** [comment]
Now accessible from pause menu between waves
